### PR TITLE
GIF Tag and Centred Statuses

### PR DESCRIPTION
**Pull request by xenrelle**
adds the gif tag asset to the repository since it doesnt seem to want to show up when using discord's asset

and also centres the status emoji again

### CODE REVIEW

**Comment by xenrelle** [comment]
not sure why the centred status emoji thing was removed in the first place but maybe it was conflicting with something else idk, i have found any issues with it yet though

**Comment by xenrelle** [comment]
and moved the favourite button back to the right as well

**Comment by DaMoyai** [comment]
> not sure why the centred status emoji thing was removed in the first place but maybe it was conflicting with something else idk, i have found any issues with it yet though

accident

**Comment by xenrelle** [comment]
all good

**Comment by DaMoyai** [comment]
kinda late, but the url didnt load because you have to add `https://discord.com` at the beginning, otherwise it thinks the file is in the repository

**Comment by xenrelle** [comment]
ohhh okay, my bad. i still think it'll be better to keep it in the repository just in case discord takes it down or anything

**Comment by DaMoyai** [comment]
yeah, my thought too

**Pull request merged**
